# Generated by Django 4.1.3 on 2023-05-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_stages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encadrant',
        ),
        migrations.RenameField(
            model_name='encadrent',
            old_name='profile',
            new_name='Type_Encadrant',
        ),
        migrations.RenameField(
            model_name='encadrent',
            old_name='numero_de_telephone',
            new_name='numero',
        ),
    ]
